### ISSUE TITLE
BMP/ICON detection is failing

### ISSUE THREAD

**Issue by Kikobeats** [dooman87/imagemagick-docker#20]
Hello,

When I was creating the Ubuntu image, I noted a strange BMP/ICO behavior, and one of my libraries that work with binaries created by the docker image [was not working as expected](https://github.com/dooman87/imagemagick-docker/pull/16#issuecomment-958950230).

In order to better understand what's happening, I tried to isolate the minimal piece of code to reproduce the error.

I created https://github.com/Kikobeats/ico-issue repo that makes the issue reproducible. Relevant files:

- [success report](https://github.com/Kikobeats/ico-issue/blob/master/reports/success-local.txt) (on my local, an MBP)
- [failed report](https://github.com/Kikobeats/ico-issue/blob/master/reports/failed-docker.txt) (using the docker image)
- [the docker log installation](https://github.com/Kikobeats/ico-issue/blob/master/reports/docker.log)

My guess is it's an issue related to something different at the CPU architecture level and how binaries are built, but there is too much thing in that space I'm skipping 

Happy if you can take a look to check if something looks wrong to you. The Dockerfile there is a copy/paste of the ubuntu version (because [entrypoint is not helping](https://github.com/dooman87/imagemagick-docker/pull/19)

**Comment by dooman87** [comment]
From what it looks like sharp is not using IM, but libvips. Is `vibrant` using ImageMagick?

**Comment by Kikobeats** [comment]
Hmm looks like [node-vibrant is using shap](https://github.com/microlinkhq/splashy/blob/master/src/vibrant.js#L15) and sharp is using [livbips](https://github.com/lovell/sharp/blob/f37ca8249afcd26777b7e3e1d0192640572341ef/docs/install.md#prebuilt-binaries)

how different IM and libvips are?

**Comment by dooman87** [comment]
IM and libvips are two different projects that don't have any dependencies on each other. I think you don't need IM (ImageMagick) in your case.

**Comment by Kikobeats** [comment]
@dooman87 looks like that's right, but I found something strange.

First I started doing things from a "fresh" state, meaning I first uninstall `imagemagick` and `vips` via `brew`. This is the output:

```
$ node index.js

node -e "console.log(process.platform)":
darwin

node -e "console.log(process.arch)":
x64

node --version:
v16.13.0

npm --version:
8.2.0


  splashy:error  +0ms
FAILED []
```

After that, I tried just installing `vips`:

```
brew install vips
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/manifests/7.1.0-17
Already downloaded: /Users/kikobeats/Library/Caches/Homebrew/downloads/62ca6b133564445b8a9c3c9d3500dda4afb832ac09bded7bbeeabab32a9edf89--imagemagick-7.1.0-17.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/blobs/sha256:8531c518d953f5
Already downloaded: /Users/kikobeats/Library/Caches/Homebrew/downloads/05b1b13fe5b162865ac8085edddfcaa57ff79816fe28488b2d649e87bf6e1b13--imagemagick--7.1.0-17.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/vips/manifests/8.12.1
Already downloaded: /Users/kikobeats/Library/Caches/Homebrew/downloads/c9e1fd070c1489cd35fb5bf89b61e720ce9927948b3581dcfdee9118f42abd46--vips-8.12.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/vips/blobs/sha256:3ca7cf19414b876ca30e4
Already downloaded: /Users/kikobeats/Library/Caches/Homebrew/downloads/bf9a886c902be1acec91bb95157625cea5e3c001f99c02493b800dc9b18cb190--vips--8.12.1.big_sur.bottle.tar.gz
==> Installing dependencies for vips: imagemagick
==> Installing vips dependency: imagemagick
==> Pouring imagemagick--7.1.0-17.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/7.1.0-17: 801 files, 30.4MB
==> Installing vips
==> Pouring vips--8.12.1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/vips/8.12.1: 165 files, 13.6MB
==> Running `brew cleanup vips`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

~/Downloads/ico-issue master* 30s
❯ node
Welcome to Node.js v16.13.0.
Type ".help" for more information.
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>

~/Downloads/ico-issue master*
❯

~/Downloads/ico-issue master*
❯ node index.js

node -e "console.log(process.platform)":
darwin

node -e "console.log(process.arch)":
x64

node --version:
v16.13.0

npm --version:
8.2.0


SUCCESS [ '#fabe14', '#816002', '#86b1f8', '#54a894', '#956f03', '#a0d5a5' ]
```

Now it worked 🤔 vips is installing `imagemagick`; what if I uninstall `imagemagick`, keeping `vips` in my system?

so this hapenned:

```
brew uninstall --ignore-dependencies imagemagick
Uninstalling /usr/local/Cellar/imagemagick/7.1.0-17... (801 files, 30.4MB)

~/Downloads/ico-issue master*
❯ node index.js
/Users/kikobeats/Projects/microlink/splashy/node_modules/sharp/lib/sharp.js:30
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

dlopen(/Users/kikobeats/Projects/microlink/splashy/node_modules/sharp/build/Release/sharp-darwin-x64.node, 1): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.10.dylib
  Referenced from: /usr/local/opt/vips/lib/libvips-cpp.42.dylib
  Reason: image not found

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=darwin --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/kikobeats/Projects/microlink/splashy/node_modules/sharp/lib/sharp.js:30:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kikobeats/Projects/microlink/splashy/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

so the library needs ImageMagick because it's using a dynamic library vips. 

Am I right?

**Comment by dooman87** [comment]
Oh, I'm sorry it looks like `libvips` use IM indeed. Found this in their configuration script: https://github.com/libvips/libvips/blob/master/configure.ac#L543

It might be using it to read BMP/ICO file.

**Comment by dooman87** [comment]
I'm curious what happens if on your local you uninstall vips and install Imagemagick then try to run your application.

Could it be the case that `vips` in npm built differently to what in brew? From their config script it looks like it might work differently when you have IM6 or IM7 installed

**Comment by Kikobeats** [comment]
@dooman87 I did that, and in that way, the code is failing

```
❯ brew uninstall vips
Uninstalling /opt/homebrew/Cellar/vips/8.12.1... (165 files, 13.7MB)

~/Downloads/ico-issue master
❯ brew install Imagemagick
Warning: imagemagick 7.1.0-17 is already installed and up-to-date.
To reinstall 7.1.0-17, run:
  brew reinstall imagemagick

~/Downloads/ico-issue master
❯ node index.js
/Users/kikobeats/Downloads/ico-issue/node_modules/.pnpm/sharp@0.29.3/node_modules/sharp/lib/sharp.js:30
  throw new Error(help.join('\n'));
  ^

Error:
Something went wrong installing the "sharp" module

dlopen(/Users/kikobeats/Downloads/ico-issue/node_modules/.pnpm/sharp@0.29.3/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node, 0x0001): Library not loaded: /opt/homebrew/opt/vips/lib/libvips-cpp.42.dylib
  Referenced from: /Users/kikobeats/Downloads/ico-issue/node_modules/.pnpm/sharp@0.29.3/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
  Reason: tried: '/opt/homebrew/opt/vips/lib/libvips-cpp.42.dylib' (no such file), '/usr/local/lib/libvips-cpp.42.dylib' (no such file), '/usr/lib/libvips-cpp.42.dylib' (no such file)

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=darwin --arch=arm64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Users/kikobeats/Downloads/ico-issue/node_modules/.pnpm/sharp@0.29.3/node_modules/sharp/lib/sharp.js:30:9)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/kikobeats/Downloads/ico-issue/node_modules/.pnpm/sharp@0.29.3/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)

Node.js v17.2.0

~/Downloads/ico-issue master
❯ rm -rf node_modules/

~/Downloads/ico-issue master
❯ npm i
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 193 packages, and audited 194 packages in 33s

13 packages are looking for funding
  run `npm fund` for details

11 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

~/Downloads/ico-issue master 32s
❯ g s

~/Downloads/ico-issue master
❯ node index.js

node -e "console.log(process.platform)":
darwin

node -e "console.log(process.arch)":
arm64

node --version:
v17.2.0

npm --version:
8.2.0

convert --version:
Version: ImageMagick 7.1.0-17 Q16-HDRI arm 2021-12-04 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Compiler: gcc (4.2)

convert -list format:
   Format  Module    Mode  Description
-------------------------------------------------------------------------------
      3FR  DNG       r--   Hasselblad CFV/H3D39II
      3G2  VIDEO     r--   Media Container
      3GP  VIDEO     r--   Media Container
      AAI* AAI       rw+   AAI Dune image
       AI  PDF       rw-   Adobe Illustrator CS2
     APNG  VIDEO     rw+   Animated Portable Network Graphics
      ART* ART       rw-   PFS: 1st Publisher Clip Art
      ARW  DNG       r--   Sony Alpha Raw Image Format
   ASHLAR* ASHLAR    -w+   Image sequence laid out in continuous irregular courses
      AVI  VIDEO     r--   Microsoft Audio/Visual Interleaved
     AVIF* HEIC      rw+   AV1 Image File Format (1.12.0)
      AVS* AVS       rw+   AVS X image
      BGR* BGR       rw+   Raw blue, green, and red samples
     BGRA* BGR       rw+   Raw blue, green, red, and alpha samples
     BGRO* BGR       rw+   Raw blue, green, red, and opacity samples
      BMP* BMP       rw-   Microsoft Windows bitmap image
     BMP2* BMP       rw-   Microsoft Windows bitmap image (V2)
     BMP3* BMP       rw-   Microsoft Windows bitmap image (V3)
      BRF* BRAILLE   -w-   BRF ASCII Braille format
      CAL* CALS      rw-   Continuous Acquisition and Life-cycle Support Type 1
           Specified in MIL-R-28002 and MIL-PRF-28002
     CALS* CALS      rw-   Continuous Acquisition and Life-cycle Support Type 1
           Specified in MIL-R-28002 and MIL-PRF-28002
   CANVAS* XC        r--   Constant image uniform color
  CAPTION* CAPTION   r--   Caption
      CIN* CIN       rw-   Cineon Image File
      CIP* CIP       -w-   Cisco IP phone image format
     CLIP* CLIP      rw+   Image Clip Mask
     CMYK* CMYK      rw+   Raw cyan, magenta, yellow, and black samples
    CMYKA* CMYK      rw+   Raw cyan, magenta, yellow, black, and alpha samples
      CR2  DNG       r--   Canon Digital Camera Raw Image Format
      CR3  DNG       r--   Canon Digital Camera Raw Image Format
      CRW  DNG       r--   Canon Digital Camera Raw Image Format
     CUBE* CUBE      r--   Cube LUT
      CUR* ICON      rw-   Microsoft icon
      CUT* CUT       r--   DR Halo
     DATA* INLINE    rw+   Base64-encoded inline images
      DCM* DCM       r--   Digital Imaging and Communications in Medicine image
           DICOM is used by the medical community for images like X-rays.  The
           specification, "Digital Imaging and Communications in Medicine
           (DICOM)", is available at http://medical.nema.org/.  In particular,
           see part 5 which describes the image encoding (RLE, JPEG, JPEG-LS),
           and supplement 61 which adds JPEG-2000 encoding.
      DCR  DNG       r--   Kodak Digital Camera Raw Image File
    DCRAW  DNG       r--   Raw Photo Decoder (dcraw)
      DCX* PCX       rw+   ZSoft IBM PC multi-page Paintbrush
      DDS* DDS       rw+   Microsoft DirectDraw Surface
    DFONT* TTF       r--   Multi-face font package (Freetype 2.11.0)
      DNG  DNG       r--   Digital Negative
      DOT  DOT       ---   Graphviz
      DPX* DPX       rw-   SMPTE 268M-2003 (DPX 2.0)
           Digital Moving Picture Exchange Bitmap, Version 2.0.
           See SMPTE 268M-2003 specification at http://www.smtpe.org

     DXT1* DDS       rw+   Microsoft DirectDraw Surface
     DXT5* DDS       rw+   Microsoft DirectDraw Surface
     EPDF  PDF       rw-   Encapsulated Portable Document Format
      EPI  PS        rw-   Encapsulated PostScript Interchange format
      EPS  PS        rw-   Encapsulated PostScript
     EPS2  PS2       -w-   Level II Encapsulated PostScript
     EPS3  PS3       -w+   Level III Encapsulated PostScript
     EPSF  PS        rw-   Encapsulated PostScript
     EPSI  PS        rw-   Encapsulated PostScript Interchange format
      EPT  EPT       rw-   Encapsulated PostScript with TIFF preview
     EPT2  EPT       rw-   Encapsulated PostScript Level II with TIFF preview
     EPT3  EPT       rw+   Encapsulated PostScript Level III with TIFF preview
      ERF  DNG       r--   Epson RAW Format
      EXR  EXR       rw-   High Dynamic-range (HDR) (OpenEXR 3.1.3)
 FARBFELD* FARBFELD  rw-   Farbfeld
      FAX* FAX       rw+   Group 3 FAX
           FAX machines use non-square pixels which are 1.5 times wider than
           they are tall but computer displays use square pixels, therefore
           FAX images may appear to be narrow unless they are explicitly
           resized using a geometry of "150x100%".

       FF* FARBFELD  rw-   Farbfeld
     FILE* URL       r--   Uniform Resource Locator (file://)
     FITS* FITS      rw-   Flexible Image Transport System
     FL32* FL32      rw-   FilmLight
      FLV  VIDEO     rw+   Flash Video Stream
  FRACTAL* PLASMA    r--   Plasma fractal image
      FTP* URL       r--   Uniform Resource Locator (ftp://)
      FTS* FITS      rw-   Flexible Image Transport System
       G3* FAX       rw-   Group 3 FAX
       G4* FAX       rw-   Group 4 FAX
      GIF* GIF       rw+   CompuServe graphics interchange format
    GIF87* GIF       rw-   CompuServe graphics interchange format (version 87a)
 GRADIENT* GRADIENT  r--   Gradual linear passing from one shade to another
     GRAY* GRAY      rw+   Raw gray samples
    GRAYA* GRAY      rw+   Raw gray and alpha samples
   GROUP4* TIFF      rw-   Raw CCITT Group4
       GV  DOT       ---   Graphviz
     HALD* HALD      r--   Identity Hald color lookup table image
      HDR* HDR       rw+   Radiance RGBE image format
     HEIC* HEIC      rw+   High Efficiency Image Format (1.12.0)
     HEIF* HEIC      rw+   High Efficiency Image Format (1.12.0)
HISTOGRAM* HISTOGRAM -w-   Histogram of the image
      HRZ* HRZ       rw-   Slow Scan TeleVision
      HTM* HTML      -w-   Hypertext Markup Language and a client-side image map
     HTML* HTML      -w-   Hypertext Markup Language and a client-side image map
     HTTP* URL       r--   Uniform Resource Locator (http://)
    HTTPS* URL       r--   Uniform Resource Locator (https://)
      ICB* TGA       rw-   Truevision Targa image
      ICO* ICON      rw+   Microsoft icon
     ICON* ICON      rw-   Microsoft icon
      IIQ  DNG       r--   Phase One Raw Image Format
     INFO  INFO      -w+   The image format and characteristics
   INLINE* INLINE    rw+   Base64-encoded inline images
      IPL* IPL       rw+   IPL Image Sequence
   ISOBRL* BRAILLE   -w-   ISO/TR 11548-1 format
  ISOBRL6* BRAILLE   -w-   ISO/TR 11548-1 format 6dot
      J2C* JP2       rw-   JPEG-2000 Code Stream Syntax (2.4.0)
      J2K* JP2       rw-   JPEG-2000 Code Stream Syntax (2.4.0)
      JNG* PNG       rw-   JPEG Network Graphics
           See http://www.libpng.org/pub/mng/ for details about the JNG
           format.
      JNX* JNX       r--   Garmin tile format
      JP2* JP2       rw-   JPEG-2000 File Format Syntax (2.4.0)
      JPC* JP2       rw-   JPEG-2000 Code Stream Syntax (2.4.0)
      JPE* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
     JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
      JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
      JPM* JP2       rw-   JPEG-2000 File Format Syntax (2.4.0)
      JPS* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
      JPT* JP2       rw-   JPEG-2000 File Format Syntax (2.4.0)
     JSON  JSON      -w+   The image format and characteristics
      K25  DNG       r--   Kodak Digital Camera Raw Image Format
      KDC  DNG       r--   Kodak Digital Camera Raw Image Format
   KERNEL* KERNEL    -w-   Morphology Kernel
    LABEL* LABEL     r--   Image label
      M2V  VIDEO     rw+   MPEG Video Stream
      M4V  VIDEO     rw+   Raw VIDEO-4 Video
      MAC* MAC       r--   MAC Paint
      MAP* MAP       rw-   Colormap intensities and indices
     MASK* MASK      rw+   Image Clip Mask
      MAT  MAT       rw+   MATLAB level 5 image format
    MATTE* MATTE     -w+   MATTE format
      MEF  DNG       r--   Mamiya Raw Image File
     MIFF* MIFF      rw+   Magick Image File Format
      MKV  VIDEO     rw+   Multimedia Container
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.6.37)
           See http://www.libpng.org/pub/mng/ for details about the MNG
           format.
     MONO* MONO      rw-   Raw bi-level bitmap
      MOV  VIDEO     rw+   MPEG Video Stream
      MP4  VIDEO     rw+   VIDEO-4 Video Stream
      MPC* MPC       rw+   Magick Pixel Cache image format
     MPEG  VIDEO     rw+   MPEG Video Stream
      MPG  VIDEO     rw+   MPEG Video Stream
      MRW  DNG       r--   Sony (Minolta) Raw Image File
      MSL* MSL       rw+   Magick Scripting Language
     MSVG* SVG       rw+   ImageMagick's own SVG internal renderer
      MTV* MTV       rw+   MTV Raytracing image format
      MVG* MVG       rw-   Magick Vector Graphics
      NEF  DNG       r--   Nikon Digital SLR Camera Raw Image File
      NRW  DNG       r--   Nikon Digital SLR Camera Raw Image File
     NULL* NULL      rw-   Constant image of uniform color
      ORA  ORA       ---   OpenRaster format
      ORF  DNG       r--   Olympus Digital Camera Raw Image File
      OTB* OTB       rw-   On-the-air bitmap
      OTF* TTF       r--   Open Type font (Freetype 2.11.0)
      PAL* UYVY      rw-   16bit/pixel interleaved YUV
     PALM* PALM      rw+   Palm pixmap
      PAM* PNM       rw+   Common 2-dimensional bitmap format
    PANGO* PANGO     ---   Pango Markup Language
  PATTERN* PATTERN   r--   Predefined pattern
      PBM* PNM       rw+   Portable bitmap format (black and white)
      PCD* PCD       rw-   Photo CD
     PCDS* PCD       rw-   Photo CD
      PCL  PCL       rw+   Printer Control Language
      PCT* PICT      rw-   Apple Macintosh QuickDraw/PICT
      PCX* PCX       rw-   ZSoft IBM PC Paintbrush
      PDB* PDB       rw+   Palm Database ImageViewer Format
      PDF  PDF       rw+   Portable Document Format
     PDFA  PDF       rw+   Portable Document Archive Format
      PEF  DNG       r--   Pentax Electronic File
      PES* PES       r--   Embrid Embroidery Format
      PFA* TTF       r--   Postscript Type 1 font (ASCII) (Freetype 2.11.0)
      PFB* TTF       r--   Postscript Type 1 font (binary) (Freetype 2.11.0)
      PFM* PNM       rw+   Portable float format
      PGM* PNM       rw+   Portable graymap format (gray scale)
      PGX* PGX       rw-   JPEG 2000 uncompressed format
      PHM* PNM       rw+   Portable half float format
    PICON* XPM       rw-   Personal Icon
     PICT* PICT      rw-   Apple Macintosh QuickDraw/PICT
      PIX* PIX       r--   Alias/Wavefront RLE image format
    PJPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
   PLASMA* PLASMA    r--   Plasma fractal image
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.37)
           See http://www.libpng.org/ for details about the PNG format.
    PNG00* PNG       rw-   PNG inheriting bit-depth, color-type from original, if possible
    PNG24* PNG       rw-   opaque or binary transparent 24-bit RGB (zlib 1.2.11)
    PNG32* PNG       rw-   opaque or transparent 32-bit RGBA
    PNG48* PNG       rw-   opaque or binary transparent 48-bit RGB
    PNG64* PNG       rw-   opaque or transparent 64-bit RGBA
     PNG8* PNG       rw-   8-bit indexed with optional binary transparency
      PNM* PNM       rw+   Portable anymap
POCKETMOD  PDF       rw+   Pocketmod Personal Organizer
      PPM* PNM       rw+   Portable pixmap format (color)
       PS  PS        rw+   PostScript
      PS2  PS2       -w+   Level II PostScript
      PS3  PS3       -w+   Level III PostScript
      PSB* PSD       rw+   Adobe Large Document Format
      PSD* PSD       rw+   Adobe Photoshop bitmap
     PTIF* TIFF      rw+   Pyramid encoded TIFF
      PWP* PWP       r--   Seattle Film Works
RADIAL-GRADIENT* GRADIENT  r--   Gradual radial passing from one shade to another
      RAF  DNG       r--   Fuji CCD-RAW Graphic File
      RAS* SUN       rw+   SUN Rasterfile
      RAW  DNG       r--   Raw
      RGB* RGB       rw+   Raw red, green, and blue samples
   RGB565* RGB       r--   Raw red, green, blue samples in 565 format
     RGBA* RGB       rw+   Raw red, green, blue, and alpha samples
     RGBO* RGB       rw+   Raw red, green, blue, and opacity samples
      RGF* RGF       rw-   LEGO Mindstorms EV3 Robot Graphic Format (black and white)
      RLA* RLA       r--   Alias/Wavefront image
      RLE* RLE       r--   Utah Run length encoded image
      RMF  DNG       r--   Raw Media Format
      RW2  DNG       r--   Panasonic Lumix Raw Image
      SCR* SCR       r--   ZX-Spectrum SCREEN$
      SCT* SCT       r--   Scitex HandShake
      SFW* SFW       r--   Seattle Film Works
      SGI* SGI       rw+   Irix RGB image
    SHTML* HTML      -w-   Hypertext Markup Language and a client-side image map
      SIX* SIXEL     rw-   DEC SIXEL Graphics Format
    SIXEL* SIXEL     rw-   DEC SIXEL Graphics Format
SPARSE-COLOR* TXT       -w+   Sparse Color
      SR2  DNG       r--   Sony Raw Format 2
      SRF  DNG       r--   Sony Raw Format
  STEGANO* STEGANO   r--   Steganographic image
      SUN* SUN       rw+   SUN Rasterfile
      SVG* SVG       rw+   Scalable Vector Graphics (XML 2.9.4)
     SVGZ* SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.4)
     TEXT* TXT       r--   Text
      TGA* TGA       rw-   Truevision Targa image
THUMBNAIL* THUMBNAIL -w+   EXIF Profile Thumbnail
     TIFF* TIFF      rw+   Tagged Image File Format (LIBTIFF, Version 4.3.0)
   TIFF64* TIFF      rw+   Tagged Image File Format (64-bit) (LIBTIFF, Version 4.3.0)
     TILE* TILE      r--   Tile image with a texture
      TIM* TIM       r--   PSX TIM
      TM2* TIM2      r--   PS2 TIM2
      TTC* TTF       r--   TrueType font collection (Freetype 2.11.0)
      TTF* TTF       r--   TrueType font (Freetype 2.11.0)
      TXT* TXT       rw+   Text
     UBRL* BRAILLE   -w-   Unicode Text format
    UBRL6* BRAILLE   -w-   Unicode Text format 6dot
      UIL* UIL       -w-   X-Motif UIL table
     UYVY* UYVY      rw-   16bit/pixel interleaved YUV
      VDA* TGA       rw-   Truevision Targa image
    VICAR* VICAR     rw-   VICAR rasterfile format
      VID* VID       rw+   Visual Image Directory
     VIFF* VIFF      rw+   Khoros Visualization image
     VIPS* VIPS      rw+   VIPS image
      VST* TGA       rw-   Truevision Targa image
     WBMP* WBMP      rw-   Wireless Bitmap (level 0) image
     WEBM  VIDEO     rw+   Open Web Media
     WEBP* WEBP      rw+   WebP Image Format (libwebp 1.2.1 [020F])
      WMV  VIDEO     rw+   Windows Media Video
      WPG* WPG       r--   Word Perfect Graphics
      X3F  DNG       r--   Sigma Camera RAW Picture File
      XBM* XBM       rw-   X Windows system bitmap (black and white)
       XC* XC        r--   Constant image uniform color
      XCF* XCF       r--   GIMP image
      XPM* XPM       rw-   X Windows system pixmap (color)
      XPS  XPS       r--   Microsoft XML Paper Specification
       XV* VIFF      rw+   Khoros Visualization image
     YAML  YAML      -w+   The image format and characteristics
    YCbCr* YCbCr     rw+   Raw Y, Cb, and Cr samples
   YCbCrA* YCbCr     rw+   Raw Y, Cb, Cr, and alpha samples
      YUV* YUV       rw-   CCIR 601 4:1:1 or 4:2:2

* native blob support
r read support
w write support
+ support for multiple images


  splashy:error  +0ms
FAILED []
```

so sharp is providing [ready-compiled](https://sharp.pixelplumbing.com/install#prebuilt-binaries) libvips that is failing 🤔

**Comment by dooman87** [comment]
This doesn't look like docker image issue, so closing it for now
